apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: {{ .Release.Namespace }}
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:3.141.59
          ports:
            - containerPort: 4442  # Event Bus Publish
            - containerPort: 4443  # Event Bus Subscribe
            - containerPort: 4444  # Selenium Grid
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: selenium-hub
  ports:
    - port: 4442
      targetPort: 4442
      name: event-bus-publish
    - port: 4443
      targetPort: 4443
      name: event-bus-subscribe
    - port: 4444
      targetPort: 4444
      name: grid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  namespace: {{ .Release.Namespace }}
  labels:
    app: selenium-node-chrome
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:3.141.59
          env:
            - name: HUB_HOST
              value: selenium-hub
            - name: HUB_PORT
              value: "4444"
            - name: NODE_MAX_SESSION
              value: "4"
            - name: NODE_SESSION_TIMEOUT
              value: "60"
          ports:
            - containerPort: 5555
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
